// Session lifecycle (whitepaper section 8 "Project and session", phase 9):
// gd_project_scaffold, gd_editor_launch, and gd_editor_quit. These are
// broker-side tools: scaffold runs before any editor exists (the one capability
// that by definition cannot require one), and launch/quit own the editor
// process from outside it.
//
// Scaffold writes project files directly. That is sanctioned here and only
// here: the no-direct-file-writes rule of section 6.5 protects a live editor
// session, and scaffold's contract is that no editor has ever opened the
// project.

import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { setTimeout as sleep } from "node:timers/promises";

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

import { AddonError, detectAddon, installAddon } from "../addon.ts";
import type { BridgeManager, EditorProcess } from "../bridge-manager.ts";
import { editorPresence, foreignEditorAdvice } from "../editor-presence.ts";
import { EngineError, installEngine, listInstalledEngines } from "../godot-install.ts";
import { engineDir } from "../godot-locate.ts";
import type { GodotResolver } from "../godot-locate.ts";
import { searchedLocations } from "../godot-locate.ts";
import { BridgeError } from "../ipc-client.ts";
import { textResult, toToolError } from "../tool-helpers.ts";

const EDITOR_CONNECT_TIMEOUT_MS = 60_000;
const EDITOR_QUIT_TIMEOUT_MS = 15_000;
const LOG_TAIL_BYTES = 4_096;

export interface SessionToolOptions {
  godot: GodotResolver;
  projectPath: string | null;
  runtimeDir: string;
  addonSource: string | null;
  version: string;
  /** Root the engine installer writes into (--engine-dir / CONDUIT_ENGINE_DIR). */
  engineDir?: string;
  /** CONDUIT_ENGINE_SOURCE: a local zip or directory instead of the download. */
  engineSource?: string | null;
  /** Records the outcome so gd_status can report it (see index.ts). */
  onInstallOutcome?: (outcome: { error: string | null; source: string | null }) => void;
}

const RUNTIME_SCENE = '[gd_scene format=3]\n\n[node name="ConduitRuntime" type="ConduitRuntime"]\n';

function libraryFileName(): string {
  switch (process.platform) {
    case "win32":
      return "conduit.dll";
    case "darwin":
      return "libconduit.dylib";
    default:
      return "libconduit.so";
  }
}

// The .gdextension library keys Godot resolves on this host. Both build types
// map to the one copied library: a wrong or missing key fails silently (the
// extension just never loads), so the keys must match the host exactly.
function gdextensionKeys(): string[] {
  switch (process.platform) {
    case "win32":
      return ["windows.debug.x86_64", "windows.release.x86_64"];
    case "darwin":
      return ["macos.debug", "macos.release"];
    default:
      return ["linux.debug.x86_64", "linux.release.x86_64"];
  }
}

// Development default: the workspace cargo output relative to this source file
// (broker/src/tools -> repo root), preferring the debug build. A distributed
// broker passes an explicit library path instead.
function defaultLibraryPath(): string | null {
  const repoRoot = path.resolve(import.meta.dir, "..", "..", "..");
  const name = libraryFileName();
  for (const build of ["debug", "release"]) {
    const candidate = path.join(repoRoot, "target", build, name);
    if (fs.existsSync(candidate)) {
      return candidate;
    }
  }
  return null;
}

function projectGodotContent(projectName: string): string {
  return [
    "; Generated by Conduit gd_project_scaffold.",
    "",
    "config_version=5",
    "",
    "[application]",
    "",
    `config/name="${projectName.replaceAll('"', "")}"`,
    "",
    "[autoload]",
    "",
    'ConduitRuntime="*res://addons/conduit/conduit_runtime.tscn"',
    "",
    "[rendering]",
    "",
    'renderer/rendering_method="gl_compatibility"',
    'renderer/rendering_method.mobile="gl_compatibility"',
    "",
  ].join("\n");
}

function gdextensionContent(libraryName: string): string {
  const lines = [
    "[configuration]",
    'entry_symbol = "gdext_rust_init"',
    "compatibility_minimum = 4.4",
    "reloadable = true",
    "",
    "[libraries]",
  ];
  for (const key of gdextensionKeys()) {
    lines.push(`${key} = "res://addons/conduit/${libraryName}"`);
  }
  lines.push("");
  return lines.join("\n");
}

/** Write the scaffold files into targetDir. Exported for unit tests. */
export function scaffoldProject(targetDir: string, projectName: string, libraryPath: string, force: boolean): string[] {
  const projectFile = path.join(targetDir, "project.godot");
  if (!force && fs.existsSync(projectFile)) {
    throw new BridgeError({
      code: "already_exists",
      message: `${projectFile} already exists; pass force=true to overwrite the scaffold files`,
      retryable: false,
    });
  }
  if (!fs.existsSync(libraryPath)) {
    throw new BridgeError({
      code: "bridge_library_not_found",
      message: `no bridge library at ${libraryPath}; build it with 'cargo build' in bridge/ or pass 'library'`,
      retryable: false,
    });
  }

  const addonDir = path.join(targetDir, "addons", "conduit");
  fs.mkdirSync(addonDir, { recursive: true });

  const libraryName = path.basename(libraryPath);
  const written: string[] = [];
  const write = (relative: string, content: string) => {
    fs.writeFileSync(path.join(targetDir, relative), content);
    written.push(relative);
  };
  write("project.godot", projectGodotContent(projectName));
  write(path.join("addons", "conduit", "conduit_runtime.tscn"), RUNTIME_SCENE);
  write(path.join("addons", "conduit", "conduit.gdextension"), gdextensionContent(libraryName));

  // Copy rather than reference: the scaffold target may sit on a different
  // drive than the build output (no res://../ traversal exists across drives),
  // and shipping the library inside addons/conduit matches section 15.
  const libraryDest = path.join(addonDir, libraryName);
  fs.copyFileSync(libraryPath, libraryDest);
  written.push(path.join("addons", "conduit", libraryName));

  return written;
}

function editorLogPath(runtimeDir: string): string {
  return path.join(runtimeDir, "conduit-editor.log");
}

function readLogTail(logPath: string): string {
  try {
    const content = fs.readFileSync(logPath, "utf8");
    return content.length > LOG_TAIL_BYTES ? content.slice(-LOG_TAIL_BYTES) : content;
  } catch {
    return "";
  }
}

export function registerSessionTools(
  server: McpServer,
  manager: BridgeManager,
  options: SessionToolOptions,
): void {
  server.registerTool(
    "gd_project_scaffold",
    {
      description:
        "Create a minimal Godot project in a directory: project.godot with the ConduitRuntime autoload, the bridge addon scene and .gdextension, and a copy of the bridge library. Runs entirely broker-side, so it needs no editor; follow with gd_editor_launch to open the project.",
      inputSchema: {
        path: z.string().describe("Target directory; defaults to the broker's configured project path.").optional(),
        project_name: z.string().describe("Project name for project.godot (default 'Conduit Project').").optional(),
        library: z.string().describe("Path to the built bridge library; defaults to the workspace cargo output.").optional(),
        force: z.boolean().describe("Overwrite scaffold files if project.godot already exists.").optional(),
      },
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
    },
    async (args) => {
      try {
        const targetDir = (args.path as string | undefined) ?? options.projectPath;
        if (!targetDir) {
          throw new BridgeError({
            code: "invalid_args",
            message: "no target directory: pass 'path' or start the broker with --project",
            retryable: false,
          });
        }
        const library = (args.library as string | undefined) ?? defaultLibraryPath();
        if (!library) {
          // defaultLibraryPath resolves the workspace cargo output, which does
          // not exist for a broker installed from npm. gd_addon_install is the
          // path that fetches a prebuilt library instead of building one.
          throw new BridgeError({
            code: "bridge_library_not_found",
            message:
              "no built bridge library found in the workspace; pass 'library', or build it with 'cargo build' in bridge/. To set up an existing project instead, use gd_addon_install, which fetches the prebuilt addon for this broker's version",
            retryable: false,
          });
        }
        const resolved = path.resolve(targetDir);
        fs.mkdirSync(resolved, { recursive: true });
        const written = scaffoldProject(resolved, (args.project_name as string | undefined) ?? "Conduit Project", library, args.force === true);
        return textResult({ path: resolved, files: written });
      } catch (error) {
        return toToolError(error);
      }
    },
  );

  server.registerTool(
    "gd_addon_install",
    {
      description:
        "Install or repair the Conduit addon in the configured Godot project: fetch the addon matching this broker's version, write addons/conduit/, and register the ConduitRuntime autoload in project.godot. Reports the current state without installing when nothing needs doing. Requires that no editor is running, because Godot only loads a new GDExtension at startup.",
      inputSchema: {
        force: z.boolean().describe("Reinstall even when the addon is already present or was installed by hand.").optional(),
        source: z
          .string()
          .describe("Override the addon source: a local zip, an unpacked directory, or a URL. Defaults to the matching GitHub release.")
          .optional(),
        autoload: z.boolean().describe("Register the ConduitRuntime autoload in project.godot (default true).").optional(),
      },
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: true },
    },
    async (args) => {
      const source = (args.source as string | undefined) ?? options.addonSource;
      try {
        if (!options.projectPath) {
          throw new BridgeError({
            code: "invalid_args",
            message: "no project configured; start the broker with --project or CONDUIT_PROJECT",
            retryable: false,
          });
        }
        // A connected editor has already loaded (or failed to load) the
        // extension, and it owns project.godot for the rest of its session.
        if (manager.isEditorConnected()) {
          throw new BridgeError({
            code: "editor_running",
            message:
              "an editor bridge is connected; close the Godot editor before installing the addon, because a newly added GDExtension is only loaded at editor startup",
            retryable: true,
          });
        }
        const result = await installAddon({
          projectPath: options.projectPath,
          version: options.version,
          source,
          autoload: args.autoload as boolean | undefined,
          force: args.force === true,
        });
        options.onInstallOutcome?.({ error: null, source: result.source });
        return textResult({
          ...result,
          next_step: "open the project in Godot so the extension loads, then the editor tools become available",
        });
      } catch (error) {
        options.onInstallOutcome?.({
          error: error instanceof Error ? error.message : String(error),
          source: source ?? null,
        });
        if (error instanceof AddonError) {
          return toToolError(new BridgeError({ code: error.code, message: error.message, retryable: error.retryable }));
        }
        return toToolError(error);
      }
    },
  );

  server.registerTool(
    "gd_addon_status",
    {
      description:
        "Report whether the configured directory is a Godot project, whether the Conduit addon is installed, whether its version matches this broker, and whether the ConduitRuntime autoload is registered.",
      inputSchema: {},
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    },
    async () => {
      try {
        if (!options.projectPath) {
          throw new BridgeError({
            code: "invalid_args",
            message: "no project configured; start the broker with --project or CONDUIT_PROJECT",
            retryable: false,
          });
        }
        return textResult({
          project_path: options.projectPath,
          expected_version: options.version,
          ...detectAddon(options.projectPath, options.version),
        });
      } catch (error) {
        return toToolError(error);
      }
    },
  );

  server.registerTool(
    "gd_engine_status",
    {
      description:
        "Report whether a Godot engine binary is available and whether one is already running. Call this before gd_editor_launch or gd_engine_install: an editor the human already has open needs neither. Reports the resolved binary and where it came from, any Godot process this broker did not start, and which engine builds this broker has installed.",
      inputSchema: {},
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    },
    async () => {
      try {
        const resolved = options.godot.resolve();
        const presence = await editorPresence(manager, options.projectPath);
        return textResult({
          binary: resolved?.path ?? null,
          source: resolved?.source ?? null,
          searched: resolved ? undefined : searchedLocations(),
          engine_dir: options.engineDir ?? engineDir(),
          installed: listInstalledEngines(options.engineDir ?? engineDir()),
          editor_connected: presence.connected,
          editor_running_unbridged: presence.foreign.length > 0,
          running_processes: presence.foreign,
          process_probe_ran: presence.probed,
          advice: foreignEditorAdvice(presence),
        });
      } catch (error) {
        return toToolError(error);
      }
    },
  );

  server.registerTool(
    "gd_engine_install",
    {
      description:
        "Download and install a Godot editor into the broker's engine directory, then use it for gd_editor_launch. Only needed when no engine is present: check gd_engine_status first, because an editor already running needs none. Installs the standard build unless mono=true, which installs the .NET build for C# projects.",
      inputSchema: {
        version: z
          .string()
          .describe('Release tag such as "4.7.1-stable". Omitted installs the latest stable release.')
          .optional(),
        mono: z.boolean().describe("Install the .NET/C# build (Godot Mono) instead of the standard one.").optional(),
        source: z.string().describe("A local zip or directory to install from instead of downloading.").optional(),
        force: z.boolean().describe("Replace an install already in that directory.").optional(),
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    },
    async (args) => {
      try {
        const presence = await editorPresence(manager, options.projectPath);
        const result = await installEngine({
          version: (args.version as string | undefined) ?? null,
          mono: args.mono === true,
          engineDir: options.engineDir ?? engineDir(),
          source: (args.source as string | undefined) ?? options.engineSource ?? null,
          force: args.force === true,
        });
        // A newly installed engine is only useful if resolution stops returning
        // the cached "nothing found" from before it existed.
        options.godot.reset();
        return textResult({
          ...result,
          // Reported rather than refused: installing the .NET build while a
          // standard editor is open is legitimate. The agent still needs to know
          // it may have been unnecessary.
          editor_connected: presence.connected,
          note: presence.connected
            ? "an editor was already connected; this install was probably unnecessary"
            : (foreignEditorAdvice(presence) ?? undefined),
        });
      } catch (error) {
        if (error instanceof EngineError) {
          return toToolError(new BridgeError({ code: error.code, message: error.message, retryable: error.retryable }));
        }
        return toToolError(error);
      }
    },
  );

  server.registerTool(
    "gd_editor_launch",
    {
      description:
        "Launch the Godot editor on the broker's configured project and wait for its bridge to connect. The engine binary is found automatically (PATH, then the usual install locations); --godot or CONDUIT_GODOT overrides that. headless=true runs the editor without a window, which is how scripted sessions drive it.",
      inputSchema: {
        headless: z.boolean().describe("Run the editor with --headless (no window).").optional(),
        force: z
          .boolean()
          .describe("Launch even though another Godot process is running. Only when you know it is unrelated.")
          .optional(),
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    },
    async (args) => {
      try {
        if (manager.isEditorConnected()) {
          throw new BridgeError({
            code: "already_connected",
            message: "an editor bridge is already connected; call gd_editor_quit first",
            retryable: false,
          });
        }
        if (manager.getEditorProcess() != null) {
          throw new BridgeError({
            code: "already_connected",
            message: "a launched editor process is still starting or running; call gd_editor_quit first",
            retryable: true,
          });
        }
        // Launching is optional, and a second editor on one project is worse
        // than not launching at all: Godot expects to own project.godot for its
        // session. An editor the human opened is invisible to both guards above,
        // so ask the machine rather than assuming absence.
        if (args.force !== true) {
          const advice = foreignEditorAdvice(await editorPresence(manager, options.projectPath));
          if (advice) {
            throw new BridgeError({
              code: "editor_running_unbridged",
              message: `${advice} Pass force=true to launch anyway if that process belongs to another project.`,
              retryable: false,
            });
          }
        }

        const godot = options.godot.resolve();
        if (!godot) {
          throw new BridgeError({
            code: "godot_binary_not_found",
            message: `no Godot engine binary found; searched ${searchedLocations().join(", ")}. Set --godot <path> or CONDUIT_GODOT, or open the project in the editor yourself and the broker will attach to it`,
            retryable: false,
          });
        }
        if (!options.projectPath) {
          throw new BridgeError({
            code: "invalid_args",
            message: "no project configured; start the broker with --project or CONDUIT_PROJECT",
            retryable: false,
          });
        }

        const headless = args.headless === true;
        const logPath = editorLogPath(options.runtimeDir);
        const spawnArgs = ["--editor", "--path", options.projectPath];
        if (headless) {
          spawnArgs.push("--headless");
        }
        spawnArgs.push("--log-file", logPath);

        const proc = spawn(godot.path, spawnArgs, {
          detached: true,
          stdio: "ignore",
          env: { ...process.env, CONDUIT_RUNTIME_DIR: options.runtimeDir },
        });
        // The editor must outlive a broker restart (section 7.5).
        proc.unref();
        manager.setEditorProcess(proc as unknown as EditorProcess);

        let exited = false;
        proc.once("exit", () => {
          exited = true;
          if (manager.getEditorProcess() === (proc as unknown as EditorProcess)) {
            manager.setEditorProcess(null);
          }
        });

        // A cold project's first open imports before extensions settle, so the
        // connect window is generous; an early process exit is a definite
        // failure worth reporting immediately with the editor's log tail.
        const deadline = Date.now() + EDITOR_CONNECT_TIMEOUT_MS;
        while (Date.now() < deadline) {
          if (exited) {
            throw new BridgeError({
              code: "editor_launch_failed",
              message: `the editor process exited before its bridge connected; log tail: ${readLogTail(logPath) || "(empty)"}`,
              retryable: false,
            });
          }
          try {
            const hello = await manager.ensureEditorConnected(2_000);
            return textResult({
              launched: true,
              pid: proc.pid,
              headless,
              engine_version: hello.engine_version,
              engine_binary: godot.path,
              engine_binary_source: godot.source,
            });
          } catch {
            // Keep waiting until the overall deadline.
          }
        }
        throw new BridgeError({
          code: "editor_launch_failed",
          message: `the editor started but its bridge did not connect within ${EDITOR_CONNECT_TIMEOUT_MS / 1000}s; log tail: ${readLogTail(logPath) || "(empty)"}`,
          retryable: true,
        });
      } catch (error) {
        return toToolError(error);
      }
    },
  );

  server.registerTool(
    "gd_editor_quit",
    {
      description:
        "Ask the connected editor to quit, then confirm it exited. Unsaved editor state is discarded. When the broker launched the editor itself, a hung process is killed as a fallback and reported as forced.",
      inputSchema: {},
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
    },
    async () => {
      try {
        const proc = manager.getEditorProcess();
        if (!manager.isEditorConnected() && !proc) {
          throw new BridgeError({
            code: "editor_unavailable",
            message: "no editor bridge is connected and the broker owns no editor process",
            retryable: true,
          });
        }

        if (manager.isEditorConnected()) {
          // The bridge acks, then quits a few frames later so the ack flushes;
          // confirmation below is what proves the exit actually happened.
          await manager.editorRequest("gd_editor_quit", {});
        }

        const deadline = Date.now() + EDITOR_QUIT_TIMEOUT_MS;
        if (proc) {
          while (Date.now() < deadline) {
            if (proc.exitCode != null || manager.getEditorProcess() == null) {
              manager.setEditorProcess(null);
              return textResult({ quit: true, forced: false });
            }
            await sleep(200);
          }
          proc.kill();
          manager.setEditorProcess(null);
          return textResult({ quit: true, forced: true });
        }

        // Adopted editor (not spawned by this broker): the socket closing is
        // the only confirmation available.
        while (Date.now() < deadline) {
          if (!manager.isEditorConnected()) {
            return textResult({ quit: true, forced: false, confirmed: "socket_closed" });
          }
          await sleep(200);
        }
        throw new BridgeError({
          code: "timeout",
          message: "the editor acknowledged the quit but its bridge connection did not close in time",
          retryable: true,
        });
      } catch (error) {
        return toToolError(error);
      }
    },
  );
}
