// Session lifecycle (whitepaper section 8 "Project and session", phase 9):
// gd_project_scaffold, gd_editor_launch, and gd_editor_quit. These are
// broker-side tools: scaffold runs before any editor exists (the one capability
// that by definition cannot require one), and launch/quit own the editor
// process from outside it.
//
// Scaffold writes project files directly. That is sanctioned here and only
// here: the no-direct-file-writes rule of section 6.5 protects a live editor
// session, and scaffold's contract is that no editor has ever opened the
// project.

import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { setTimeout as sleep } from "node:timers/promises";

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

import type { BridgeManager, EditorProcess } from "../bridge-manager.ts";
import { BridgeError } from "../ipc-client.ts";
import { textResult, toToolError } from "../tool-helpers.ts";

const EDITOR_CONNECT_TIMEOUT_MS = 60_000;
const EDITOR_QUIT_TIMEOUT_MS = 15_000;
const LOG_TAIL_BYTES = 4_096;

export interface SessionToolOptions {
  godotBin: string | null;
  projectPath: string | null;
  runtimeDir: string;
}

const RUNTIME_SCENE = '[gd_scene format=3]\n\n[node name="ConduitRuntime" type="ConduitRuntime"]\n';

function libraryFileName(): string {
  switch (process.platform) {
    case "win32":
      return "conduit.dll";
    case "darwin":
      return "libconduit.dylib";
    default:
      return "libconduit.so";
  }
}

// The .gdextension library keys Godot resolves on this host. Both build types
// map to the one copied library: a wrong or missing key fails silently (the
// extension just never loads), so the keys must match the host exactly.
function gdextensionKeys(): string[] {
  switch (process.platform) {
    case "win32":
      return ["windows.debug.x86_64", "windows.release.x86_64"];
    case "darwin":
      return ["macos.debug", "macos.release"];
    default:
      return ["linux.debug.x86_64", "linux.release.x86_64"];
  }
}

// Development default: the workspace cargo output relative to this source file
// (broker/src/tools -> repo root), preferring the debug build. A distributed
// broker passes an explicit library path instead.
function defaultLibraryPath(): string | null {
  const repoRoot = path.resolve(import.meta.dir, "..", "..", "..");
  const name = libraryFileName();
  for (const build of ["debug", "release"]) {
    const candidate = path.join(repoRoot, "target", build, name);
    if (fs.existsSync(candidate)) {
      return candidate;
    }
  }
  return null;
}

function projectGodotContent(projectName: string): string {
  return [
    "; Generated by Conduit gd_project_scaffold.",
    "",
    "config_version=5",
    "",
    "[application]",
    "",
    `config/name="${projectName.replaceAll('"', "")}"`,
    "",
    "[autoload]",
    "",
    'ConduitRuntime="*res://addons/conduit/conduit_runtime.tscn"',
    "",
    "[rendering]",
    "",
    'renderer/rendering_method="gl_compatibility"',
    'renderer/rendering_method.mobile="gl_compatibility"',
    "",
  ].join("\n");
}

function gdextensionContent(libraryName: string): string {
  const lines = [
    "[configuration]",
    'entry_symbol = "gdext_rust_init"',
    "compatibility_minimum = 4.4",
    "reloadable = true",
    "",
    "[libraries]",
  ];
  for (const key of gdextensionKeys()) {
    lines.push(`${key} = "res://addons/conduit/${libraryName}"`);
  }
  lines.push("");
  return lines.join("\n");
}

/** Write the scaffold files into targetDir. Exported for unit tests. */
export function scaffoldProject(targetDir: string, projectName: string, libraryPath: string, force: boolean): string[] {
  const projectFile = path.join(targetDir, "project.godot");
  if (!force && fs.existsSync(projectFile)) {
    throw new BridgeError({
      code: "already_exists",
      message: `${projectFile} already exists; pass force=true to overwrite the scaffold files`,
      retryable: false,
    });
  }
  if (!fs.existsSync(libraryPath)) {
    throw new BridgeError({
      code: "bridge_library_not_found",
      message: `no bridge library at ${libraryPath}; build it with 'cargo build' in bridge/ or pass 'library'`,
      retryable: false,
    });
  }

  const addonDir = path.join(targetDir, "addons", "conduit");
  fs.mkdirSync(addonDir, { recursive: true });

  const libraryName = path.basename(libraryPath);
  const written: string[] = [];
  const write = (relative: string, content: string) => {
    fs.writeFileSync(path.join(targetDir, relative), content);
    written.push(relative);
  };
  write("project.godot", projectGodotContent(projectName));
  write(path.join("addons", "conduit", "conduit_runtime.tscn"), RUNTIME_SCENE);
  write(path.join("addons", "conduit", "conduit.gdextension"), gdextensionContent(libraryName));

  // Copy rather than reference: the scaffold target may sit on a different
  // drive than the build output (no res://../ traversal exists across drives),
  // and shipping the library inside addons/conduit matches section 15.
  const libraryDest = path.join(addonDir, libraryName);
  fs.copyFileSync(libraryPath, libraryDest);
  written.push(path.join("addons", "conduit", libraryName));

  return written;
}

function editorLogPath(runtimeDir: string): string {
  return path.join(runtimeDir, "conduit-editor.log");
}

function readLogTail(logPath: string): string {
  try {
    const content = fs.readFileSync(logPath, "utf8");
    return content.length > LOG_TAIL_BYTES ? content.slice(-LOG_TAIL_BYTES) : content;
  } catch {
    return "";
  }
}

export function registerSessionTools(
  server: McpServer,
  manager: BridgeManager,
  options: SessionToolOptions,
): void {
  server.registerTool(
    "gd_project_scaffold",
    {
      description:
        "Create a minimal Godot project in a directory: project.godot with the ConduitRuntime autoload, the bridge addon scene and .gdextension, and a copy of the bridge library. Runs entirely broker-side, so it needs no editor; follow with gd_editor_launch to open the project.",
      inputSchema: {
        path: z.string().describe("Target directory; defaults to the broker's configured project path.").optional(),
        project_name: z.string().describe("Project name for project.godot (default 'Conduit Project').").optional(),
        library: z.string().describe("Path to the built bridge library; defaults to the workspace cargo output.").optional(),
        force: z.boolean().describe("Overwrite scaffold files if project.godot already exists.").optional(),
      },
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
    },
    async (args) => {
      try {
        const targetDir = (args.path as string | undefined) ?? options.projectPath;
        if (!targetDir) {
          throw new BridgeError({
            code: "invalid_args",
            message: "no target directory: pass 'path' or start the broker with --project",
            retryable: false,
          });
        }
        const library = (args.library as string | undefined) ?? defaultLibraryPath();
        if (!library) {
          throw new BridgeError({
            code: "bridge_library_not_found",
            message: "no built bridge library found in the workspace; build it with 'cargo build' in bridge/ or pass 'library'",
            retryable: false,
          });
        }
        const resolved = path.resolve(targetDir);
        fs.mkdirSync(resolved, { recursive: true });
        const written = scaffoldProject(resolved, (args.project_name as string | undefined) ?? "Conduit Project", library, args.force === true);
        return textResult({ path: resolved, files: written });
      } catch (error) {
        return toToolError(error);
      }
    },
  );

  server.registerTool(
    "gd_editor_launch",
    {
      description:
        "Launch the Godot editor on the broker's configured project with the configured engine binary (--godot or CONDUIT_GODOT) and wait for its bridge to connect. headless=true runs the editor without a window, which is how scripted sessions drive it.",
      inputSchema: {
        headless: z.boolean().describe("Run the editor with --headless (no window).").optional(),
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    },
    async (args) => {
      try {
        if (manager.isEditorConnected()) {
          throw new BridgeError({
            code: "already_connected",
            message: "an editor bridge is already connected; call gd_editor_quit first",
            retryable: false,
          });
        }
        if (manager.getEditorProcess() != null) {
          throw new BridgeError({
            code: "already_connected",
            message: "a launched editor process is still starting or running; call gd_editor_quit first",
            retryable: true,
          });
        }
        if (!options.godotBin) {
          throw new BridgeError({
            code: "godot_binary_not_configured",
            message: "no engine binary configured; start the broker with --godot <path> or CONDUIT_GODOT",
            retryable: false,
          });
        }
        if (!options.projectPath) {
          throw new BridgeError({
            code: "invalid_args",
            message: "no project configured; start the broker with --project or CONDUIT_PROJECT",
            retryable: false,
          });
        }

        const headless = args.headless === true;
        const logPath = editorLogPath(options.runtimeDir);
        const spawnArgs = ["--editor", "--path", options.projectPath];
        if (headless) {
          spawnArgs.push("--headless");
        }
        spawnArgs.push("--log-file", logPath);

        const proc = spawn(options.godotBin, spawnArgs, {
          detached: true,
          stdio: "ignore",
          env: { ...process.env, CONDUIT_RUNTIME_DIR: options.runtimeDir },
        });
        // The editor must outlive a broker restart (section 7.5).
        proc.unref();
        manager.setEditorProcess(proc as unknown as EditorProcess);

        let exited = false;
        proc.once("exit", () => {
          exited = true;
          if (manager.getEditorProcess() === (proc as unknown as EditorProcess)) {
            manager.setEditorProcess(null);
          }
        });

        // A cold project's first open imports before extensions settle, so the
        // connect window is generous; an early process exit is a definite
        // failure worth reporting immediately with the editor's log tail.
        const deadline = Date.now() + EDITOR_CONNECT_TIMEOUT_MS;
        while (Date.now() < deadline) {
          if (exited) {
            throw new BridgeError({
              code: "editor_launch_failed",
              message: `the editor process exited before its bridge connected; log tail: ${readLogTail(logPath) || "(empty)"}`,
              retryable: false,
            });
          }
          try {
            const hello = await manager.ensureEditorConnected(2_000);
            return textResult({
              launched: true,
              pid: proc.pid,
              headless,
              engine_version: hello.engine_version,
            });
          } catch {
            // Keep waiting until the overall deadline.
          }
        }
        throw new BridgeError({
          code: "editor_launch_failed",
          message: `the editor started but its bridge did not connect within ${EDITOR_CONNECT_TIMEOUT_MS / 1000}s; log tail: ${readLogTail(logPath) || "(empty)"}`,
          retryable: true,
        });
      } catch (error) {
        return toToolError(error);
      }
    },
  );

  server.registerTool(
    "gd_editor_quit",
    {
      description:
        "Ask the connected editor to quit, then confirm it exited. Unsaved editor state is discarded. When the broker launched the editor itself, a hung process is killed as a fallback and reported as forced.",
      inputSchema: {},
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
    },
    async () => {
      try {
        const proc = manager.getEditorProcess();
        if (!manager.isEditorConnected() && !proc) {
          throw new BridgeError({
            code: "editor_unavailable",
            message: "no editor bridge is connected and the broker owns no editor process",
            retryable: true,
          });
        }

        if (manager.isEditorConnected()) {
          // The bridge acks, then quits a few frames later so the ack flushes;
          // confirmation below is what proves the exit actually happened.
          await manager.editorRequest("gd_editor_quit", {});
        }

        const deadline = Date.now() + EDITOR_QUIT_TIMEOUT_MS;
        if (proc) {
          while (Date.now() < deadline) {
            if (proc.exitCode != null || manager.getEditorProcess() == null) {
              manager.setEditorProcess(null);
              return textResult({ quit: true, forced: false });
            }
            await sleep(200);
          }
          proc.kill();
          manager.setEditorProcess(null);
          return textResult({ quit: true, forced: true });
        }

        // Adopted editor (not spawned by this broker): the socket closing is
        // the only confirmation available.
        while (Date.now() < deadline) {
          if (!manager.isEditorConnected()) {
            return textResult({ quit: true, forced: false, confirmed: "socket_closed" });
          }
          await sleep(200);
        }
        throw new BridgeError({
          code: "timeout",
          message: "the editor acknowledged the quit but its bridge connection did not close in time",
          retryable: true,
        });
      } catch (error) {
        return toToolError(error);
      }
    },
  );
}
