[package]
name = "conduit"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
godot.workspace = true
interprocess.workspace = true
crossbeam-channel.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
